Table Users {
  user_id int [pk]
  first_name string [not null]
  last_name string
  email string [not null]
  password_hash string [not null]
}

Table Addresses {
  id int [pk]
  user_id int [not null, ref: > Users.user_id]
  city string [not null]
  street string [not null]
  house string [not null]
  apartment string
}


Table DefaultPizza {
  pizza_id int [pk]
  name string [not null]
  price decimal [not null]
}


Table Orders {
  order_id int [pk]
  user_id int [not null, ref: > Users.user_id]
  total_cost decimal [not null] // Полная стоимость заказа
  order_date datetime [not null]
  order_status string [not null]
}

Table OrderItems {
  item_id int [pk]
  order_id int [not null, ref: > Orders.order_id]
  pizza_id int [not null, ref: > DefaultPizza.pizza_id]
  quantity int [not null]
}


Table Promo_Codes {
  promo_id int [pk]
  code string [unique, not null] // Промокод
  discount_percentage int [not null]
  start_date datetime [not null]
  end_date datetime [not null]
}
